platform :ios, '7.0'

target "NewMediaApp" do
pod 'AFNetworking', '~> 3.1.0'
pod 'Masonry'
pod 'JSONModel'
pod 'SDWebImage', '~> 3.7.1'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'ReactiveCocoa'
pod 'TTTAttributedLabel', '~> 1.13.4'
pod 'MWPhotoBrowser', '~> 2.1.1'
pod 'NJKWebViewProgress'
pod 'pop', '~> 1.0.8'
pod 'Base64nl', '~> 1.2'
pod 'UITableView+FDTemplateLayoutCell', '~> 1.5.beta'
pod 'UITextView+Placeholder', '~> 1.1.0'
pod 'ShareSDK3'
pod 'MOBFoundation'
pod 'ShareSDK3/ShareSDKUI'
pod 'ShareSDK3/ShareSDKPlatforms/QQ'
pod 'ShareSDK3/ShareSDKPlatforms/SinaWeibo'
pod 'ShareSDK3/ShareSDKPlatforms/WeChat'
pod 'LUKeychainAccess', '~> 1.2.5'
pod 'YYKit'
end